### ISSUE TITLE
Placement service 1.0.0-rc.1 is not displayed on Dashboard

### ISSUE THREAD

**Issue by artursouza** [dapr/dashboard#101]
Install Dapr v1.0.0-rc.1.
dapr dashboard -k

See placement service is not listed below.

![image](https://user-images.githubusercontent.com/130954/99024708-f8982f80-251b-11eb-9b24-67c68e961719.png)

**Comment by mukundansundar** [comment]
Potentially need to change this 
https://github.com/dapr/dashboard/blob/c907deb916da67094ef15e90e563a4ec6c343609/pkg/instances/instances.go#L33

**Comment by youngbupark** [comment]
> Potentially need to change this
> https://github.com/dapr/dashboard/blob/c907deb916da67094ef15e90e563a4ec6c343609/pkg/instances/instances.go#L33

yeah we can just add `dapr-placement-server` in this list to fix this issue.
