### ISSUE TITLE
Show metrics setting in Configurations

### ISSUE THREAD

**Issue by artursouza** [dapr/dashboard#103]
Show metrics setting in Configurations summary:

![image](https://user-images.githubusercontent.com/130954/99470846-4e911c80-28fa-11eb-8bad-2c93f940f7f3.png)

parent: #93

**Comment by msfussell** [comment]
This issue is dependent on this one https://github.com/dapr/cli/issues/487

**Comment by artursouza** [comment]
Metrics is enabled on a per deployment basis. So, it is displayed in the app summary and not in the config summary.

See https://github.com/dapr/dashboard/pull/114

**Comment by artursouza** [comment]
I've created an issue to discuss a migration for the metrics config to the Configuration CRD: https://github.com/dapr/dapr/issues/2515
