### ISSUE TITLE
Dashboard shows rows of Dapr apps with blank details

### ISSUE THREAD

**Issue by AaronCrawfis** [dapr/dashboard#118]
## Expected Behavior

Dashboard shows apps running on AKS cluster

## Actual Behavior

Dashboard shows rows with blank information

![image](https://user-images.githubusercontent.com/54363786/101060682-87f59900-3544-11eb-815f-f890f77f0be3.png)
![image](https://user-images.githubusercontent.com/54363786/101060741-99d73c00-3544-11eb-85df-ace656f18812.png)

**Comment by artursouza** [comment]
Please, use dashboard version 0.4.0. This issue has been fixed already in #87
