### ISSUE TITLE
Please, provide a docker image that I can use right away

### ISSUE THREAD

**Issue by andrecarlucci** [dapr/dashboard#13]
I would love to do a docker run and have the dashboard up and running :)

**Comment by yaron2** [comment]
that's a bit of a problem since the dashboard needs to reach out to localhost, and that's a no-no with containers.

But, we are working on a command as simple as `dapr dashboard` which will automagically spin up the dashboard for you, Dockerless :)

**Comment by andrecarlucci** [comment]
Awesome, that would be even better.
Cheers!

**Comment by shalabhms** [comment]
@andrecarlucci , with [Dapr 0.9.0 release](https://github.com/dapr/dapr/releases) - you can `dapr dashboard -k ` to spin the dashboard.
