### ISSUE TITLE
dapr app port annotation in instances API

### ISSUE THREAD

**Issue by pnocera** [dapr/dashboard#150]
## Expected Behavior

in instances.go line 28
daprPortAnnotation    = "dapr.io/port"
should be
daprPortAnnotation    = "dapr.io/app-port"

**Comment by yaron2** [comment]
@pnocera would you like to submit a PR to fix this?

**Comment by fabrizziocht** [comment]
Hello @yaron2 , I've just sent a PR.
Regards,
Fabri
