### ISSUE TITLE
build.sh fails to build on macOS

### ISSUE THREAD

**Issue by gdhuper** [dapr/dashboard#16]
### Issue description:
`build.sh` has hardcoded `GOOS` variable to `linux`, hence it fails on macOS.

![Screen Shot 2020-06-11 at 9 55 30 AM](https://user-images.githubusercontent.com/11465335/84417066-f37c3080-abc9-11ea-9ac9-895ac16a99ab.png)

Changing `export GOOS=linux` to `export GOOS=darwin` in `build.sh` works fine. 

### Possible solutions:
- Update the documentation to call this out
- Set `GOOS` value based on the target OS in `build.sh`

**Comment by amanbha** [comment]
@gdhuper build.sh has been updated, please try with it, build.sh is used in github actions as well to prepare release. I am closing this, please close this, if issue still happen. After running build.sh, binaries will be in the release folder for linux, darwin and windows.
