### ISSUE TITLE
Dashboard Configuration section is blank on version 1.4.0

### ISSUE THREAD

**Issue by espenairmine** [dapr/dashboard#171]
## Expected Behavior

The Dashboard Config section should display config information

## Actual Behavior

The Dashboard Config section displays a list of configs, but when clicking on one of them, the screen is blank,
Both for <Summary> and <Applications>

## Steps to Reproduce the Problem

Install 1.4.0 on a clean cluster
Or upgrade from 1.3.0

![image](https://user-images.githubusercontent.com/51234981/134672752-1e555b45-0538-4c78-89c5-c8991a6d46a1.png)
![image](https://user-images.githubusercontent.com/51234981/134672817-853f5ed6-ad90-4dd1-aec1-6c7b375e7d09.png)

**Comment by l0ll098** [comment]
Hi @espenairmine,
this is a bug accidentally introduced with the latest version of the Dapr dashboard (that is being used by Dapr 1.4.X). I've already opened a PR to fix this issue #170. Once that gets merged, it will be fixed and be back working as usual.
