### ISSUE TITLE
Add action to filter logs

### ISSUE THREAD

**Issue by willdavsmith** [dapr/dashboard#48]
In the application detail view 'logs' tab, a user should be able to filter logs based on severity or any other keyword. This should update the list of logs displayed to the user and highlight the search term. By default, all logs should be shown.

User should be able to view logs. 
User should be able to search in the logs. 
User should be able to filter the log level in the view. 
User should be able to select application logs. 
User should be able to select the Daprd logs. 
User should be able to go to next page ( pagination support ) in the logs view.

**Comment by shalabhms** [comment]
Some of the following 2 required features in this issue have been released in Dapr 0.9.0 release.

User should be able to view logs.
User should be able to filter the log level in the view.
