### ISSUE TITLE
Multiple kubeconfigs in KUBECONFIG environment variable

### ISSUE THREAD

**Issue by Johnsonxd4** [dapr/dashboard#62]
Hello,

I'm using dapr running on minikube.
But, when i try to start the dashboard running the command "dapr dashboard -k", i received the message:

"Failed to initialize kubernetes client: multiple kubeconfigs in KUBECONFIG environment variable"

I do have multiple kubeconfig in my KUBECONFIG variable, and i manage it by [kubectx](https://github.com/ahmetb/kubectx).

Is there any way i can select my context, or which kubeconfig i'm referring when starting the dashboard?

Best regards

**Comment by amanbha** [comment]
Please select the cluster using ```kubectl config use-context``` command before using dapr cli commands, it will use the selected config.
With kubectx, does ```kubectx <NAME>``` name works before running the dapr cli command?

**Comment by Johnsonxd4** [comment]
I tried using both commands, but i received the same error. None of then worked. I received the  same error:
Can't connect to a Kubernetes cluster: multiple kubeconfigs in KUBECONFIG environment variable - /home/johnson/.kube/config:/home/johnson/.kube/wms-2nd.kubeconfig

It is a problem for dapr configuration to have multiple configuration files in KUBECONFIG variable?

**Comment by Johnsonxd4** [comment]
Closing this issue, I'll open it again in the project [dapr-cli](https://github.com/dapr/cli).
