### ISSUE TITLE
Provide containerized version of dashboard

### ISSUE THREAD

**Issue by tomkerkhove** [dapr/dashboard#72]
Provide containerized version of dashboard so that it can be deployed in the cluster allowing teams to use the same tool without having to install anything.

**Comment by yaron2** [comment]
Its already installed by default with 0.9.0.

**Comment by tomkerkhove** [comment]
That's a very stupid request from my side 🤦‍♂️

It's there indeed and just need to add an ingress; thank you!

**Comment by yaron2** [comment]
> That's a very stupid request from my side 🤦‍♂️
> 
> It's there indeed and just need to add an ingress; thank you!

If you have the latest Dapr CLI, you can just run `dapr dashboard --kubernetes` and it will port-forward securely and open it in your browser :)

You can also port-forward yourself so get the name of the dashboard pod and then run `kubectl port-forward <pod-name> -n dapr-system 8080:8080`. It'll then be available on `localhost:8080`.
