### ISSUE TITLE
Please, consider adding support for ARM architecture

### ISSUE THREAD

**Issue by lgramatikov** [dapr/dashboard#75]
Hello,

I am trying to install dapr 0.10.0 on [k3s](https://github.com/rancher/k3s) running on a Raspberry Pi. dapr itself works fine, but dashboard fails - its Helm chart points to a non-arm container. As a result, pod fails with "exec format error".

Also, in 0.10.0, running ```dapr init``` on a Raspberry Pi fails with "error downloading dashboard binary: version not found from url: https://github.com/dapr/dashboard/releases/download/v0.2.0/dashboard_linux_arm.tar.gz".

There is a workaround though - I did try to compile dashboard on a Pi and it "mostly" worked. Using 0.2.0 sources, I followed build.sh steps:
- ```npm i``` fails consistently, but I think it is my Pi. On Windows it works fine
- build.sh does not have arm as a platform in ```platforms```. For my local build, I adjusted build.sh as ```platforms=("linux_arm")```
- copied to Pi dist folder from Angular build I did on Windows
- ```./build.sh --generate-artifacts --release-version 0.2.0``` works as expected. It also generates dashboard_linux_arm.tar.gz
- running ```./dashboard``` locally works (```curl -v http://localhost:8080``` returns start page of the dashboard).

What's not working for me is Docker container (probably I am doing something wrong):
- ```docker build -t airiam/dapr-dashboard-unofficial-arm:0.2.0 .``` works
- executing ```docker run -it --rm -p 8080:8080 --name dapr-dashboard airiam/dapr-dashboard-unofficial-arm:0.2.0``` locally starts the container and I can see "Dapr Dashboard running on http://localhost:8080". Calling the URL (i.e. ```curl -v http://localhost:8080```) fails with "connection reset by peer". Internet said that it might be caused by wrong port mapping, but Docker command looks correct to me.

I am not sure if adding "linux_arm" to build.sh is enough given that I can't confirm that everything works locally on a Pi. Can it be Go version? On the Pi I have "go version go1.13.5 linux/arm". Thank you!

**Comment by yaron2** [comment]
Thanks for raising this issue.

We should have the dashboard work on ARM architecture, especially now that we're automatically installing it.

/cc @youngbupark @mchmarny

**Comment by yaron2** [comment]
> executing docker run -it --rm -p 8080:8080 --name dapr-dashboard airiam/dapr-dashboard-unofficial-arm:0.2.0 locally starts the container and I can see "Dapr Dashboard running on http://localhost:8080". Calling the URL (i.e. curl -v http://localhost:8080) fails with "connection reset by peer". Internet said that it might be caused by wrong port mapping, but Docker command looks correct to me.

The dashboard is meant to run as a Pod inside your k3s cluster, or if you're running Dapr outside of k8s, as a standalone process. Running it with `docker run` is not supported due to networking/filesystem limitations.

**Comment by willdavsmith** [comment]
Instead of using `docker run`, pushing to a remote image and applying a manifest file may do the trick. See https://github.com/dapr/dashboard/blob/master/docs/development/build_kubernetes.sh#L38 (Line 38 onwards) for some context. Workflow may look like the following:

1. Create dapr-dashboard-unofficial-arm.yaml (https://github.com/dapr/dashboard/blob/master/docs/development/development_guide.md#apply-new-deployment)
2. Delete old dashboard pods
3. kubectl apply -f ./dapr-dashboard-unofficial-arm.yaml
4. dapr dashboard -k

Of course, this would be a temporary workaround, and I'd love to see/ assist in adding ARM support @yaron2

**Comment by lgramatikov** [comment]
That's what I just did and I can confirm that dashboard works fine. My unofficial image is at: https://hub.docker.com/repository/docker/airiam/dapr-dashboard-unofficial-arm. If that's OK, I would like to leave it for the next couple of days and will delete it afterwards.

**Comment by yaron2** [comment]
It's your repo, you can leave it for as long as you want :)

**Comment by artursouza** [comment]
Just added support to it in the merged PR above.

**Comment by youngbupark** [comment]
@artursouza can we close it ?

**Comment by mukundansundar** [comment]
closed via https://github.com/dapr/dapr/issues/2107
