### ISSUE TITLE
Display full cmd and registered actors

### ISSUE THREAD

**Issue by aktxyz** [dapr/dashboard#78]
- summary/command is truncated, looks like showing only 20 char? results in commands like this
  ./bin/Debug/netco...

- would it be possible to list the type of actors that this app registered (ie has available), in addition to the count of actors that have actually been activated?

Parent: #93 

RELEASE NOTE: **FIXED** display of full cmd and registered actors

**Comment by yaron2** [comment]
Thanks, I think getting the list of registered actors is a very good feature.

**Comment by artursouza** [comment]
Scope for this issue:
+ List registered actors.
+ Display full command text.

**Comment by aktxyz** [comment]
+1
