### ISSUE TITLE
Dashboard doesn't run on Mac OS X

### ISSUE THREAD

**Issue by jdubois** [dapr/dashboard#92]
I installed Dapr using Homebrew (see https://github.com/dapr/docs/pull/850 )

After a successful `dapr init`, running `dapr dashboard` (to run it in standalone mode) doesn't work, here is a screenshot attached:

![Screenshot 2020-10-08 at 10 49 51](https://user-images.githubusercontent.com/316835/95437023-c90e6a00-0954-11eb-897b-9930993fc54b.png)

**Comment by Yggdrasill-7C9** [comment]
You need to install dapr runtime first
`dapr init --runtime-version 0.11.3`

**Comment by artursouza** [comment]
Closing this issue in the meantime. Please, reopen is it can still be reproduced.

**Comment by Erchoc** [comment]
![image](https://user-images.githubusercontent.com/19908809/150753935-eecae4c8-714c-4147-a6ed-7f49c513dd18.png)

i think the github api limit lead to `dapr dashboard` unavailable，how can i do for this？
