### ISSUE TITLE
Numerous improvements and issues on the Dashboard

### ISSUE THREAD

**Issue by msfussell** [dapr/dashboard#93]
Generally the dashboard should be hosting platform agnostics. Currently it looks like it is closely tied to K8s platform.

K8s mode
1) dapr-dashboard should be in the control plane list. #102 
2) Configuration tab
- Summary should include metric setting. #103
- Configurations ~~should not show K8s config and~~ the view box size for config details is too small and would be nice if this was resizable #105 
- Generally note that for config the Dapr CLI for config will change since it only shows a few settings from the control plane. This will need to be more general
3) Components tab
- Configurations ~~should not show K8s config and~~ the view box size for config details is too small and would be nice if this was resizable #106
4) App Tab
- Should be able to see list of config and components used by an application
_artursouza: Not possible without tracing data since only the App's code can determine if an application is using a given component._
- ~~Selector and label are K8s concepts. Are these needed here on the summary and why?~~
_artursouza: The DaprApplications list shows columns specific to the running platform. In standalone mode, that column (and others) are not shown at all. No need to change it._
- Configurations ~~should not show K8s config and the view the~~ view box size for config details is too small and would be nice if this was resizable #107
- The logs page freezes on a refresh. The logs are oldest at the top, but I do not want to continue to always scroll. The view box size for logs details is too small and would be nice if this was resizable. #104
- Metadata is useful, but again this is K8s specific. Do we need a mode on the dashboard that shows what hosting platform this is running on? K8s, verses Self host verses IoT edge etc
_artursouza: The dashboard renders differently in K8s mode vs standalone mode already. I think it is better to have this dynamic rendering over a static template. I don't think anything should be changed for this._
5) Control plane tab needs to show dapr in HA mode, either in the number of replicas or by saying HA mode somewhere. #108
6) When running locally I can press this dustbin icon and it stops my app without any warning. What is the actions column here supposed to do? Create, delete apps? Why only stop? #109

**Comment by artursouza** [comment]
Closing issue as all related items are now resolved.
