### ISSUE TITLE
Strongly tied to kubernetes?

### ISSUE THREAD

**Issue by dazinator** [dapr/dashboard#99]
From the README

> Dapr Dashboard is a web-based UI for Dapr, allowing users to see information, view logs and more for the Dapr applications, components, and configurations running either locally or in a Kubernetes cluster.

Does this mean the dashboard is concerned that its running either locally or in kubernetes cluster as the only two options, and it won't work hosted anywhere else? (docker compose / swarm, service fabric mesh etc)  - I'd be surprised if that were the case but the current statement makes me want to check

**Comment by msfussell** [comment]
Yes, the dashboard is not supposed to be tied to a single platform, as Dapr itsself is not ties to a single hosting platform.  However I recognize that today there are features that depend on Kubernetes, which should not be the case. Some have been raised here https://github.com/dapr/dashboard/issues/93.

**Comment by dazinator** [comment]
If you are looking for another hosting platform to validate a hosting agnostic dashboard- my vote is SF Mesh, although its been a bit quiet on that front lately - I'm hoping one day it will come out of preview but who knows :-)

**Comment by codeputer** [comment]
Just want to point out that WCF (IMO) lost against REST because it simply tried to be too much for too many configurations.

I wish DAPR was more focused on what it needs to do (.net), before we spend a lot of time on what it could be.

R

**Comment by artursouza** [comment]
As @msfussell mentioned, Dapr runs on self hosted and Kubernetes only in the meantime.

I am closing this issue. Please, reopen if there is any other question related to this discussion.
